language: python
python:
    - "3.6"
services:
 - postgresql
before_script:
- psql -c 'create database sportsmatch_api_test_db;' -U postgres
install:
- pip install pipenv
- pipenv install --dev
script:
- py.test --cov=src --cov-config .coveragerc --cov-report term-missing

# after_success:
#   - coveralls
# env:
# - TEST_DATABASE_URL="postgres://travis@localhost:3306/sportsmatch_api_test_db"
# addons:
# - postgresql: "9.3"
