"""empty message

Revision ID: 3e3a74e0dd36
Revises: 61cb8baf76db
Create Date: 2020-02-01 20:39:39.409143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3a74e0dd36'
down_revision = '61cb8baf76db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('read', sa.Boolean(), nullable=False))
    op.alter_column('sports', 'badminton',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sports', 'badminton_ability',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('sports', 'squash',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sports', 'squash_ability',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('sports', 'table_tennis',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sports', 'table_tennis_ability',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('sports', 'tennis',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sports', 'tennis_ability',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sports', 'tennis_ability',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('sports', 'tennis',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sports', 'table_tennis_ability',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('sports', 'table_tennis',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sports', 'squash_ability',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('sports', 'squash',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sports', 'badminton_ability',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('sports', 'badminton',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('messages', 'read')
    # ### end Alembic commands ###
