"""empty message

Revision ID: 40bf09a7fe15
Revises: c831288f05b2
Create Date: 2020-06-14 18:09:52.199652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bf09a7fe15'
down_revision = 'c831288f05b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('sport', sa.String(), nullable=True))
    op.add_column('results', sa.Column('sport', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'sport')
    op.drop_column('games', 'sport')
    # ### end Alembic commands ###
