"""empty message

Revision ID: 41bc1a3d3957
Revises: adefb3c0e94e
Create Date: 2020-01-17 09:38:05.709944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bc1a3d3957'
down_revision = 'adefb3c0e94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('tennis', sa.Boolean(), nullable=False),
    sa.Column('tennis_ability', sa.String(length=20), nullable=False),
    sa.Column('squash', sa.Boolean(), nullable=False),
    sa.Column('squash_ability', sa.String(length=20), nullable=False),
    sa.Column('table_tennis', sa.Boolean(), nullable=False),
    sa.Column('table_tennis_ability', sa.String(length=20), nullable=False),
    sa.Column('badminton', sa.Boolean(), nullable=False),
    sa.Column('badminton_ability', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_unique_constraint(None, 'photos', ['user_id'])
    op.alter_column('players', 'ability',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('players', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('players', 'gender',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('players', 'rank_points',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'rank_points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'gender',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('players', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('players', 'ability',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'photos', type_='unique')
    op.drop_table('sports')
    # ### end Alembic commands ###
