"""empty message

Revision ID: 44b8e1b01e75
Revises: d734a9de7a0d
Create Date: 2020-02-12 13:42:32.002705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b8e1b01e75'
down_revision = 'd734a9de7a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sports', 'badminton_ability')
    op.drop_column('sports', 'table_tennis_ability')
    op.drop_column('sports', 'tennis_ability')
    op.drop_column('sports', 'squash_ability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sports', sa.Column('squash_ability', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('sports', sa.Column('tennis_ability', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('sports', sa.Column('table_tennis_ability', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('sports', sa.Column('badminton_ability', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
