"""empty message

Revision ID: 4c0673b2bf05
Revises: a0516657354a
Create Date: 2020-02-26 14:44:27.627974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0673b2bf05'
down_revision = 'a0516657354a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('badminton', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('squash', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('table_tennis', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('tennis', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'tennis')
    op.drop_column('players', 'table_tennis')
    op.drop_column('players', 'squash')
    op.drop_column('players', 'current_user_id')
    # ### end Alembic commands ###
