"""empty message

Revision ID: 61cb8baf76db
Revises: 41bc1a3d3957
Create Date: 2020-01-17 09:50:01.506625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cb8baf76db'
down_revision = '41bc1a3d3957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sports', sa.Column('current_user_id', sa.Integer(), nullable=False))
    op.drop_constraint('sports_player_id_key', 'sports', type_='unique')
    op.create_unique_constraint(None, 'sports', ['current_user_id'])
    op.drop_constraint('sports_player_id_fkey', 'sports', type_='foreignkey')
    op.create_foreign_key(None, 'sports', 'players', ['current_user_id'], ['id'])
    op.drop_column('sports', 'player_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sports', sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sports', type_='foreignkey')
    op.create_foreign_key('sports_player_id_fkey', 'sports', 'players', ['player_id'], ['id'])
    op.drop_constraint(None, 'sports', type_='unique')
    op.create_unique_constraint('sports_player_id_key', 'sports', ['player_id'])
    op.drop_column('sports', 'current_user_id')
    # ### end Alembic commands ###
