"""empty message

Revision ID: 8db4d016d725
Revises: 44b8e1b01e75
Create Date: 2020-02-12 13:57:57.070926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db4d016d725'
down_revision = '44b8e1b01e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sports', 'badminton')
    op.drop_column('sports', 'table_tennis')
    op.drop_column('sports', 'squash')
    op.drop_column('sports', 'tennis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sports', sa.Column('tennis', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sports', sa.Column('squash', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sports', sa.Column('table_tennis', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sports', sa.Column('badminton', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
