"""empty message

Revision ID: a0516657354a
Revises: 8db4d016d725
Create Date: 2020-02-12 13:58:32.223114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0516657354a'
down_revision = '8db4d016d725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sports', sa.Column('badminton', sa.String(length=50), nullable=True))
    op.add_column('sports', sa.Column('squash', sa.String(length=50), nullable=True))
    op.add_column('sports', sa.Column('table_tennis', sa.String(length=50), nullable=True))
    op.add_column('sports', sa.Column('tennis', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sports', 'tennis')
    op.drop_column('sports', 'table_tennis')
    op.drop_column('sports', 'squash')
    op.drop_column('sports', 'badminton')
    # ### end Alembic commands ###
