"""empty message

Revision ID: adefb3c0e94e
Revises: 8311c3243e1b
Create Date: 2020-01-15 16:12:54.806966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adefb3c0e94e'
down_revision = '8311c3243e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo1', sa.LargeBinary(), nullable=True),
    sa.Column('photo2', sa.LargeBinary(), nullable=True),
    sa.Column('photo3', sa.LargeBinary(), nullable=True),
    sa.Column('photo4', sa.LargeBinary(), nullable=True),
    sa.Column('photo5', sa.LargeBinary(), nullable=True),
    sa.Column('photo6', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
