"""empty message

Revision ID: d1e1d1f1e687
Revises: 2c56b574c6ee
Create Date: 2020-05-02 21:30:22.207490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1e1d1f1e687'
down_revision = '2c56b574c6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sports')
    op.alter_column('photos', 'photo1',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=128),
               nullable=True)
    op.alter_column('photos', 'photo2',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=128),
               nullable=True)
    op.alter_column('photos', 'photo3',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=128),
               nullable=True)
    op.alter_column('photos', 'photo4',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=128),
               nullable=True)
    op.alter_column('photos', 'photo5',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=128),
               nullable=True)
    op.drop_column('photos', 'photo6')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('photo6', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.alter_column('photos', 'photo5',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('photos', 'photo4',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('photos', 'photo3',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('photos', 'photo2',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('photos', 'photo1',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.create_table('sports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('badminton', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('squash', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('table_tennis', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tennis', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_user_id'], ['players.id'], name='sports_current_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sports_pkey'),
    sa.UniqueConstraint('current_user_id', name='sports_current_user_id_key')
    )
    # ### end Alembic commands ###
